DROP TABLE IF EXISTS db;

CREATE TABLE db (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT NOT NULL,
    data_ TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    num_1 INTEGER,
    num_2 INTEGER,
    num_3 INTEGER,
    num_4 INTEGER
);